checks:
  file-lines:
    exclude_paths:
      - "**/test_*.py"
languages:
  Python: true

plugins:
  pep8:
    enabled: true
  csslint:
    enabled: false

exclude_paths:
  - "**/vendor/"
  - "**/migrations/"
  - "/test"
  -  "app/constants/"
