version: "2"

checks:
  file-lines:
    config:
      threshold: 300

plugins:
  pep8:
    enabled: true
    config:
      max-line-length: 127
  csslint:
    enabled: false

exclude_patterns:
  - "**/vendor/"
  - "**/migrations/"
  -  "app/constants/"
