version: "2"

checks:
  file-lines:
    config:
      threshold: 300

plugins:
  pep8:
    enabled: true
  csslint:
    enabled: false

exclude_patterns:
  - "**/vendor/"
  - "**/migrations/"
  -  "app/constants/"
