checks:
  file-lines:
    config:
      threshold: 300

languages:
  Python: true

plugins:
  pep8:
    enabled: true
  csslint:
    enabled: false

exclude_paths:
  - "**/vendor/"
  - "**/migrations/"
  - "/test"
  -  "app/constants/"
