# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-24 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, default='received', max_length=20, verbose_name='Status'),
        ),
    ]
