# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='customer_ref',
            field=models.CharField(blank=True, max_length=20, verbose_name='Customer Ref.'),
        ),
    ]
