# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=8)),
                ('donate_date', models.DateTimeField(verbose_name='Date Donated')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_date', models.DateTimeField(verbose_name='Date Donated')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
