# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171129_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='batch',
            field=models.CharField(blank=True, max_length=20, verbose_name='Batch'),
        ),
    ]
