# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171005_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='receipt_id',
            field=models.CharField(max_length=9),
        ),
    ]
