# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171129_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='mobile_extension',
            field=models.CharField(blank=True, max_length=10, verbose_name='MobileExt #'),
        ),
        migrations.AddField(
            model_name='donor',
            name='telephone_extension',
            field=models.CharField(blank=True, max_length=10, verbose_name='TeleExt #'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_name',
            field=models.CharField(blank=True, max_length=75, verbose_name='Donor Name'),
        ),
    ]
