# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171129_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='province',
            field=models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('ON', 'Ontario'), ('NS', 'Nova Scotia'), ('NL', 'Newfoundland and Labrador'), ('SK', 'Saskatchewan'), ('YT', 'Yukon'), ('MB', 'Manitoba'), ('NU', 'Nunavut'), ('PE', 'Prince Edward Island'), ('NT', 'Northwest Territories'), ('QC', 'Quebec'), ('NB', 'New Brunswick')], max_length=20, verbose_name='Province'),
        ),
    ]
