# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171028_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Donation & Items Verified?'),
        ),
    ]
