# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171005_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='donate_date',
            field=models.DateField(verbose_name='Date Donated'),
        ),
        migrations.AlterField(
            model_name='form',
            name='donor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='raw',
            name='donate_date',
            field=models.DateField(verbose_name='Date Donated'),
        ),
        migrations.AlterField(
            model_name='raw',
            name='donor_name',
            field=models.CharField(max_length=50),
        ),
    ]
