# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 08:16
from __future__ import unicode_literals

import app.enums.source_enum
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190730_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='source',
        ),
        migrations.AddField(
            model_name='donation',
            name='source',
            field=models.CharField(choices=[('DIRECT_MANUAL_INPUT', 'Direct Manual Input'), ('ONLINE_FORM', 'On-line Form'), ('WEBSITE_IMPORT', 'Website File Import'), ('HISTORICAL_DATA',
                                                                                                                                                                         'Historical Data'), ('THIRD_PARTY_DATA', '3rd Party Data')], default=app.enums.source_enum.SourceEnum('Direct Manual Input'), max_length=255, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pledge_date',
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name='Pledge Date'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='want_receipt',
            field=models.BooleanField(
                default=True, verbose_name='Want Tax Receipt?'),
        ),
    ]
