# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_donor_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='verified_by_reboot',
            new_name='verified',
        ),
    ]
