# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-05 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190804_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('OPENED', 'Opened'), ('IN_TEST', 'In Test'), ('EVALED', 'Evaled'), (
                'RECEIPTED', 'Receipted')], default='OPENED', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('PLEDGED', 'Pledged'), ('RECEIVED', 'Received'), ('TESTED', 'Tested'), (
                'REFURBISHED', 'Refurbished'), ('SOLD', 'Sold'), ('RECYCLED', 'Recycled')], default='PLEDGED', max_length=255, verbose_name='Status'),
        ),
    ]
