# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 23:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180526_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='tax_receipt_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
