# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_donation_tax_receipt_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'permissions': (('generate_tax_receipt', 'Can generate tax receipts'),)},
        ),
    ]
