# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 22:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180623_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='tax_receipt_created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
