# Generated by Django 2.2.10 on 2020-02-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191025_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Test Date'),
        ),
        migrations.AddField(
            model_name='donation',
            name='valuation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Valuation Date'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='tax_receipt_created_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Receipted Date'),
        ),
    ]
