# Generated by Django 2.2.10 on 2020-02-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200209_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
    ]
