# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190516_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='tax_receipt_no',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Donation Number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Donation', verbose_name='Donation Number'),
        ),
    ]
