# Generated by Django 2.2.10 on 2020-06-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200604_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdevice',
            name='make',
            field=models.CharField(
                blank=True, max_length=1024, verbose_name='Make'),
        ),
        migrations.AlterField(
            model_name='itemdevice',
            name='model',
            field=models.CharField(
                blank=True, max_length=1024, verbose_name='Model'),
        ),
    ]
