# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-29 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190613_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='province',
            field=models.CharField(choices=[('NS', 'Nova Scotia'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('AB', 'Alberta'), ('NU', 'Nunavut'), ('SK', 'Saskatchewan'), ('QC', 'Quebec'), ('NB', 'New Brunswick'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('BC', 'British Columbia'), ('NL', 'Newfoundland and Labrador'), ('MB', 'Manitoba')], max_length=20, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(choices=[('RAM', 'Ram'), ('Other Monitor', 'Other Monitor'), ('Laser Printer', 'Laser Printer'), ('HDD', 'Hard Disk Drive'), ('Other Printer', 'Other Printer'), ('MotherBoard', 'MotherBoard'), ('Speaker', 'Speaker'), ('DSLR', 'DSLR'), ('Other', 'Other'), ('Inkjet Printer', 'Inkjet Printer'), ('HeadPhone', 'Headphones'), ('Mobile Phone', 'Mobile Phone'), ('3d Printer', '3d Printer'), ('PSU', 'Power Supply'), ('Cables', 'Cables/Connectors'), ('Floppy Drive', 'Floppy Diskette'), ('Webcam', 'Webcam'), ('Switch', 'Network Switch'), ('TV', 'Television'), ('LCD Monitor', 'LCD Monitor'), ('CPU', 'CPU'), ('Tablet', 'Tablet'), ('Audio Receiver', 'Audio Receiver'), ('LiquidCooler', 'Liquid Cooler'), ('Keyboard', 'Keyboard'), ('PC-DESKTOP', 'Computer Desktop'), ('Fan', 'Fan'), ('Mic', 'Microphone'), ('Other gaming console', 'Gaming console'), ('GPU', 'Video Card'), ('Other Storage Device', 'Other Storage Device'), ('Xbox', 'Xbox'), ('LED Monitor', 'LED Monitor'), ('Other Network Device', 'Other Network Device'), ('AllInOne Printer', 'All-In-One Printer'), ('Camera', 'Camera'), ('Server', 'Server'), ('Playstation', 'Playstation'), ('Router', 'Router'), ('CCTV Camera', 'CCTV camera'), ('SSD', 'Solid State Drive'), ('PC-Laptop', 'Computer Laptop'), ('Mice', 'Mice'), ('HeatSink', 'Heat Sink')], max_length=500, verbose_name='Description'),
        ),
    ]
