# Generated by Django 2.2.10 on 2020-06-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200625_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='particulars',
            field=models.CharField(
                blank=True, max_length=1024, verbose_name='Particulars'),
        ),
    ]
