# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-29 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190628_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='province',
            field=models.CharField(choices=[('MB', 'Manitoba'), ('AB', 'Alberta'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('NS', 'Nova Scotia'), ('BC', 'British Columbia'), ('PE', 'Prince Edward Island'), ('NB', 'New Brunswick'), ('YT', 'Yukon'), ('NT', 'Northwest Territories'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('NL', 'Newfoundland and Labrador')], max_length=20, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(choices=[('HDD', 'Hard Disk Drive'), ('RAM', 'Ram'), ('Tablet', 'Tablet'), ('Other', 'Other'), ('Laser Printer', 'Laser Printer'), ('Camera', 'Camera'), ('PC-DESKTOP', 'Computer Desktop'), ('Switch', 'Network Switch'), ('Other Monitor', 'Other Monitor'), ('PSU', 'Power Supply'), ('SSD', 'Solid State Drive'), ('Webcam', 'Webcam'), ('Mobile Phone', 'Mobile Phone'), ('Floppy Drive', 'Floppy Diskette'), ('Playstation', 'Playstation'), ('CCTV Camera', 'CCTV camera'), ('Other Storage Device', 'Other Storage Device'), ('MotherBoard', 'MotherBoard'), ('Fan', 'Fan'), ('Speaker', 'Speaker'), ('Audio Receiver', 'Audio Receiver'), ('LCD Monitor', 'LCD Monitor'), ('Other Printer', 'Other Printer'), ('Server', 'Server'), ('Keyboard', 'Keyboard'), ('Mic', 'Microphone'), ('AllInOne Printer', 'All-In-One Printer'), ('Other gaming console', 'Gaming console'), ('Other Network Device', 'Other Network Device'), ('HeatSink', 'Heat Sink'), ('Xbox', 'Xbox'), ('PC-Laptop', 'Computer Laptop'), ('LiquidCooler', 'Liquid Cooler'), ('Mice', 'Mice'), ('Router', 'Router'), ('CPU', 'CPU'), ('HeadPhone', 'Headphones'), ('DSLR', 'DSLR'), ('Cables', 'Cables/Connectors'), ('GPU', 'Video Card'), ('TV', 'Television'), ('Inkjet Printer', 'Inkjet Printer'), ('LED Monitor', 'LED Monitor'), ('3d Printer', '3d Printer')], max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quality',
            field=models.CharField(choices=[('M', 'Medium'), ('L', 'Low'), ('H', 'High')], max_length=20, verbose_name='Quality'),
        ),
    ]
