# Generated by Django 2.2.10 on 2020-09-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200704_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='postal_code',
            field=models.CharField(max_length=16, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='itemdevicetype',
            name='category',
            field=models.CharField(choices=[('BATTERY', 'Battery'), ('STORAGE', 'Storage'), ('PERIPHERAL', 'Peripheral'), ('POWER_SUPPLY', 'Power Supply'), ('COMPUTER', 'Computer'), ('VIDEO', 'Video'), ('CABLE', 'Cable'), ('NETWORK', 'Network'), ('TABLET', 'Tablet'), ('DISPOSE', 'Dispose'), ('SMALL_ELECTRIC_NON_IT', 'Small Electric Non-IT'), ('CAMERA', 'Camera'), ('RECYLE', 'Recyle'), ('PRINTER', 'Printer'), ('ASSORTED', 'Assorted'), ('COMPONENT', 'Component'), ('PHONE', 'Phone'), ('CASH', 'Cash'), ('MONITOR', 'Monitor'), ('AUDIO', 'Audio'), ('SOFTWARE', 'Software'), ('MISCELLANEOUS', 'Others')], max_length=255, verbose_name='Category'),
        ),
    ]
