# Generated by Django 2.2.10 on 2021-08-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200903_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'permissions': (('generate_tax_receipt', 'Can generate tax receipts'), ('change_tax_receipt_created_at', 'Can change tax receipt created at'))},
        ),
    ]
