# Generated by Django 2.2.28 on 2023-05-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210821_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdevicetype',
            name='category',
            field=models.CharField(choices=[('BATTERY', 'Battery'), ('STORAGE', 'Storage'), ('PERIPHERAL', 'Peripheral'), ('POWER_SUPPLY', 'Power Supply'), ('COMPUTER', 'Computer'), ('VIDEO', 'Video'), ('CABLE', 'Cable'), ('CABLES', 'Cables'), ('NETWORK', 'Network'), ('TABLET', 'Tablet'), ('DISPOSE', 'Dispose'), ('SMALL_ELECTRIC_NON_IT', 'Small Electric Non-IT'), ('CAMERA', 'Camera'), ('RECYLE', 'Recyle'), ('PRINTER', 'Printer'), ('ASSORTED', 'Assorted'), ('COMPONENT', 'Component'), ('PHONE', 'Phone'), ('CASH', 'Cash'), ('MONITOR', 'Monitor'), ('AUDIO', 'Audio'), ('SOFTWARE', 'Software'), ('RECYCLE', 'Recycle'), ('MISCELLANEOUS', 'Others')], max_length=255, verbose_name='Category'),
        ),
    ]
