FIELD_NAMES = [
    "TR#",
    "Date",
    "Donor Name",
    "Address",
    "Unit",
    "City",
    "Prov.",
    "Postal Code",
    "Contact",
    "Telephone",
    "Mobile",
    "PPC",
    "TRV",
    "Email",
    "Qty",
    "Manufacturer",
    "Model",
    "Item Description",
    "Item Particulars",
    "Working",
    "Condition",
    "Quality",
    "Batch",
    "Value",
    "CustRef",
    "Status"]
