LEGACY_FIELDS = [
    "TR#",
    "Date",
    "Donor Name",
    "Address",
    "Unit",
    "City",
    "Prov.",
    "Postal Code",
    "Contact",
    "Telephone",
    "Mobile",
    "PPC",
    "TRV",
    "Email",
    "Qty",
    "Manufacturer",
    "Model",
    "Item Description",
    "Item Particulars",
    "Working",
    "Condition",
    "Quality",
    "Batch",
    "Value",
    "CustRef",
    "Status",
]


CURRENT_FIELDS = [
    "Source",
    "Pledge Date",
    "Donor Number",
    "Donor Name",
    "AddressLine1",
    "AddressLine2",
    "City",
    "Province",
    "Postal Code",
    "Contact Name (Pers)",
    "Phone Number Prime",
    "Phone Number Alt",
    "Email Address",
    "Unique Donation Identifier",
    "Receiving Date",
    "Pick Up Postal Code",
    "Tax Receipt Email/Mail/Refused",
    "Asset Tag",
    "Serial Number",
    "Make",
    "Model",
    "Device Type",
    "CPU Type",
    "Speed",
    "Memory (MB)",
    "HD Size (GB)",
    "Screen Size",
    "Notes",
    "HDD Serial Number",
    "Operating System",
    "Status",
    "Weight",
    "Valuation Date",
    "Value",
    "Valuation Supporting Doc",
    "Tax Receipt Date",
]
