LEGACY_FIELDS = [
    "TR#",
    "Date",
    "Donor Name",
    "Address",
    "Unit",
    "City",
    "Prov.",
    "Postal Code",
    "Contact",
    "Telephone",
    "Mobile",
    "PPC",
    "TRV",
    "Email",
    "Qty",
    "Manufacturer",
    "Model",
    "Item Description",
    "Item Particulars",
    "Working",
    "Condition",
    "Quality",
    "Batch",
    "Value",
    "CustRef",
    "Status",
]


CURRENT_FIELDS = [
    "Donor Name - Donor",
    "Contact Name - Donor",
    "Email - Donor",
    "Tax Receipt Via - Donor",
    "Telephone Number - Donor",
    "Address Line 1 - Donor",
    "Address Line 2 - Donor",
    "City - Donor",
    "Province - Donor",
    "Postal Code - Donor",
    "Customer Reference - Donor",
    "Tax Receipt Number - Donation",
    "Pledge Date - Donation",
    "Donate Date - Donation",
    "Test Date - Donation",
    "Valuation Date - Donation",
    "Receipted Date - Donation",
    "Pick Up Postal Code - Donation",
    "Source - Donation",
    "Quality - Item",
    "Serial Number - Item",
    "Asset Tag - Item",
    "Particulars - Item",
    "Quantity - Item",
    "Working - Item",
    "Condition - Item",
    "Batch - Item",
    "Value - Item",
    "Verified - Item",
    "Status - Item",
    "Weight - Item",
    "Valuation Date - Item",
    "Valuation Supporting Doc - Item",
    "Notes - Item",
    "Category - Item Device Type",
    "Type - Item Device Type",
    "Make - Item Device",
    "Model - Item Device",
    "CPU Type - Item Device",
    "Speed - Item Device",
    "Memory (MB) - Item Device",
    "HD SIZE (GB) - Item Device",
    "Screen Size - Item Device",
    "HDD Serial Number - Item Device",
    "Operating System - Item Device",
]

WEBFORM_FIELDS = [
    "Method of Donation",
    "reBOOT Location",
    "Tax Receipt Required",
    "Business Name (if applicable)",
    "Contact Name (First)",
    "Contact Name (Middle)",
    "Contact Name (Last)",
    "Email Address",
    "Phone Number",
    "Address (Street Address)",
    "Address (Address Line 2)",
    "Address (City)",
    "Address (State / Province)",
    "Address (ZIP / Postal Code)",
    "Address (Country)",
    "Mailing Address (Street Address)",
    "Mailing Address (Address Line 2)",
    "Mailing Address (City)",
    "Mailing Address (State / Province)",
    "Mailing Address (ZIP / Postal Code)",
    "Mailing Address (Country)",
    "Donation Items 1",
    "Donation Items 2",
    "Donation Items 3",
    "Donation Items 4",
    "Donation Items 5",
    "Donation Items 6",
    "Donation Items 7",
    "Donation Items 8",
    "Donation Items 9",
    "Donation Items 10",
    "Donation Items 11",
    "Donation Items 12",
    "Donation Items 13",
    "Donation Items 14",
    "Donation Items 15",
    "Donation Items 16",
    "Donation Items 17",
    "Donation Items 18",
    "Donation Items 19",
    "Donation Items 20",
    "Donation Items 21",
    "Donation Items 22",
    "Donation Items 23",
    "Donation Items 24",
    "Donation Items 25",
    "Donation Items 26",
    "Donation Items 27",
    "Donation Items 28",
    "Donation Items 29",
    "Donation Items 30",
    "Donation Items 31",
    "Donation Items 32",
    "Donation Items 33",
    "Donation Items 34",
    "Donation Items 35",
    "Donation Items 36",
    "Donation Items 37",
    "Donation Items 38",
    "Donation Items 39",
    "Donation Items 40",
    "Donation Items 41",
    "Donation Items 42",
    "Donation Items 43",
    "Donation Items 44",
    "Donation Items 45",
    "Donation Items 46",
    "Donation Items 47",
    "Donation Items 48",
    "Donation Items 49",
    "Donation Items 50",
    "Donation Items 51",
    "Donation Items 52",
    "Donation Items 53",
    "Donation Items 54",
    "Donation Items 55",
    "Donation Items 56",
    "Donation Items 57",
    "Donation Items 58",
    "Donation Items 59",
    "Donation Items 60",
    "Donation Items 61",
    "Donation Items 62",
    "Donation Items 63",
    "Donation Items 64",
    "Donation Items 65",
    "Donation Items 66",
    "Donation Items 67",
    "Donation Items 68",
    "Donation Items 69",
    "Donation Items 70",
    "Donation Items 71",
    "Donation Items 72",
    "Donation Items 73",
    "Donation Items 74",
    "Donation Items 75",
    "Donation Items 76",
    "Donation Items 77",
    "Donation Items 78",
    "Donation Items 79",
    "Donation Items 80",
    "Donation Items 81",
    "Donation Items 82",
    "Donation Items 83",
    "Donation Items 84",
    "Donation Items 85",
    "Donation Items 86",
    "Donation Items 87",
    "Donation Items 88",
    "Donation Items 89",
    "Donation Items 90",
    "Donation Items 91",
    "Donation Items 92",
    "Donation Items 93",
    "Donation Items 94",
    "Donation Items 95",
    "Donation Items 96",
    "Donation Items 97",
    "Donation Items 98",
    "Donation Items 99",
    "Donation Items 100",
    "Donation Items 101",
    "Donation Items 102",
    "Donation Items 103",
    "Donation Items 104",
    "Donation Items 105",
    "Donation Items 106",
    "Do you require a certificate of data erasure?",
    "Notes: (parking, buzzer, dock availability, stairs, etc.)",
    "Images or Inventory List",
    "I have reviewed my donation to ensure that it does not contain any hazardous items.",
    "1",
    "2",
    "Entry Id",
    "Entry Date",
    "User Agent",
    "User IP",
]
