QUALITY = {
    ('H', 'High'),
    ('M', 'Medium'),
    ('L', 'Low'),
}

ITEM_TYPE = {
    ('PC-DESKTOP', 'Computer Desktop'),
    ('PC-Laptop', 'Computer Laptop'),
    ('Server', 'Server'),
    ('HDD', 'Hard Disk Drive'),
    ('SSD', 'Solid State Drive'),
    ('Floppy Drive', 'Floppy Diskette'),
    ('Other Storage Device', 'Other Storage Device'),
    ('LCD Monitor', 'LCD Monitor'),
    ('LED Monitor', 'LED Monitor'),
    ('Other Monitor', 'Other Monitor'),
    ('AllInOne Printer', 'All-In-One Printer'),
    ('Inkjet Printer', 'Inkjet Printer'),
    ('Laser Printer', 'Laser Printer'),
    ('Other Printer', 'Other Printer'),
    ('Router', 'Router'),
    ('Switch', 'Network Switch'),
    ('Other Network Device', 'Other Network Device'),
    ('Keyboard', 'Keyboard'),
    ('Mice', 'Mice'),
    ('Webcam', 'Webcam'),
    ('GPU', 'Video Card'),
    ('Mic', 'Microphone'),
    ('RAM', 'Ram'),
    ('CPU', 'CPU'),
    ('HeatSink', 'Heat Sink'),
    ('HeadPhone', 'Headphones'),
    ('MotherBoard', 'MotherBoard'),
    ('PSU', 'Power Supply'),
    ('LiquidCooler', 'Liquid Cooler'),
    ('Fan', 'Fan'),
    ('Mobile Phone', 'Mobile Phone'),
    ('Cables', 'Cables/Connectors'),
    ('3d Printer', '3d Printer'),
    ('Speaker', 'Speaker'),
    ('Audio Receiver', 'Audio Receiver'),
    ('Xbox', 'Xbox'),
    ('Playstation', 'Playstation'),
    ('Other gaming console', 'Gaming console'),
    ('Camera', 'Camera'),
    ('DSLR', 'DSLR'),
    ('Tablet', 'Tablet'),
    ('CCTV Camera', 'CCTV camera'),
    ('TV', 'Television'),
    ('Other', 'Other'),
}
