UNCHANGEABLE_ERROR = 'This instance may not be modified further since the related tax receipt was generated.'
PERMISSION_DENIED = 'Permission denied. Please contact admin for access.'
UNVERIFIED_DONATION = 'Unverified donations are not valid for tax receipt generation. Please review and try again.'
UNEVALUATED_DONATION = 'Donations with not evaluated items are not valid for tax receipt generation. Please review and try again.'
RECEIPTED_DONATION = 'Donations with tax receipts already generated are not valid for tax receipt generation. Please review and try again.'
