from .resource_enum import ResourceEnum


class ItemCategoryEnum(ResourceEnum):
    BATTERY = "Battery"
    STORAGE = "Storage"
    PERIPHERAL = "Peripheral"
    POWER_SUPPLY = "Power Supply"
    COMPUTER = "Computer"
    VIDEO = "Video"
    CABLE = "Cable"
    CABLES = "Cables"
    NETWORK = "Network"
    TABLET = "Tablet"
    DISPOSE = "Dispose"
    SMALL_ELECTRIC_NON_IT = "Small Electric Non-IT"
    CAMERA = "Camera"
    RECYLE = "Recyle"
    PRINTER = "Printer"
    ASSORTED = "Assorted"
    COMPONENT = "Component"
    PHONE = "Phone"
    CASH = "Cash"
    MONITOR = "Monitor"
    AUDIO = "Audio"
    SOFTWARE = "Software"
    RECYCLE = "Recycle"
    MISCELLANEOUS = "Others"
